### ISSUE TITLE
02-CodePen-VanillaJS

### ISSUE THREAD

**Issue by Cem515** [OriginCodeAcademy/Cohort10#126]
1. Where can I find your CodePens? (Copy and paste links to each one)
https://codepen.io/cem515/pen/OmMExE?editors=1010 (Non-Functional / Calculator)

https://codepen.io/cem515/pen/LyGrxR ( To-Do List)

https://codepen.io/cem515/pen/zwrpmX (StoryTime)

	Pen #1 – A Story
 1. What is the function of document.getElementById()?
	 The function is how you reference different elements in an html. By using an elements ID, you can target a specific element with different JavaScript functions and actions.
	 2. What happens if you remove `e.preventDefault() ` on line 18 and `return false` on line 37? (Delete these lines and play around with the app)
When the two lines are removed, the story will display for a moment and then disappear.
	    Why does this happen? (Search 'e. preventDefault form' on Google)
	The two lines are what prevents the browser from using its default programming after the commands. Typically, after an event occurs the browser will end the event but by preventing default behavior with return false and prevent default the story remains up after being populated.		
	 3. How do you grab the value of an input element using JavaScript? 
	 First you should create a variable to contain the element input for cleaner code. Next you should use the getElementById command and identify which element you will be targeting. Finally, you must clarify you will be using the result by adding value syntax to the line.
Final product = “var x = document.getElementById('x').value;”
	 4. How do you set the inner HTML of a p element using JavaScript?
First you must identify which element you will input a value. Next you add the innerHTML tag to the doc element to clarify the value should be between the brackets. Next you set the value of the element with an equivalency character.
document.getElementById("story Output").innerHTML = story;

Pen # 2 A To Do List
	1. What is the function of appendChild()?
	In this function appendChild adds the new input to the end of the existing list. By appending a new li element to the end of the parent ul list it creates an organized list that pushes the new li elements to the bottom position and prevents overlap.
	2. What is the function of createElement()?
	CreateElement is what allows for the creation of a new li element to the list. By creating a new li element for every new task it allows for the list to grow rather than having a set number of tasks and requiring repeated edits to keep the list current.
	3. What is the function of createTextNode()
Create Text Node is the function that allows for the text entered into the input area to be transfixed inside of the new elements created by CreateElements. Without text node, we would create empty elements to add to the list rather than adding the task to be completed.

	
	4. How would you go about implementing a remove to do feature?
	If I were tasked to add a remove feature I would begin by designing a button element entitled “Remove”. Next I would give the buttons functionality that removed the li element it was affixed to as a click event. These features are more easily used and implemented using Angular.

Code Pen #3 Number List	

1.	What is the function of document.getElementsByTagName?
The function is intended to be able to identify an element by its name so that it can be targeted by JavaScript functionality. By targeting an element’s tag name, it allows for only a specific element to be targeted rather than every element on the page with a same type.
	 
          2. What is the purpose of the. reduce function?
Reduce is a function that condenses an array into a singular value. In this case reduce is able to target the numbers in the array and reduce them into one number, the sum.	 

3.	 What is the purpose of the setAttribute method?
The idea behind setAttribute is so that the input from the user can be turned into a specific type of object for the code to process. By transforming input into a number , string , or something else the code is able to process the input into more usable terms.

**Comment by seancahall** [comment]
Good work!
