### ISSUE TITLE
02-CodePen-VanillaJS

### ISSUE THREAD

**Issue by jennvking** [OriginCodeAcademy/Cohort10#130]
1. Where can I find your CodePens? (Copy and paste links to each one)
#1 
http://codepen.io/jennvking/pen/bWpYBy
Exercise Questions
1. What is the function of document.getElementById()?
This function returns the element that has the ID attribute with the specified value.
(Ex: var name = document.getElementById ('nameInput').value;
This returns the input for the Name element.)
2. What happens if you remove `e.preventDefault()` on line 18 and `return false` on line 37? (Delete these lines and play around with the app)
Why does this happen? (Search 'e.preventDefault form' on Google)
3. How do you grab the value of an input element using JavaScript? 
By using the document.getElementById (); function and entering in the input id set in the HTML file, you grab whatever value was set for that input id.
4. How do you set the innerHTML of a p element using JavaScript?
By applying the .innerHTML to the object

#2 
http://codepen.io/jennvking/pen/jmqZLe
Questions
1. What is the function of appendChild()?
This function create a node as the last child of a node.
EX: creating a list item (li) in an unordered list (ul).
2. What is the function of createElement()?
You can create a node (button element) with this function.
3. What is the function of createTextNode()?
You can create a text node with this function ("Hello World).
4. How would you go about implementing a remove todo feature?
You could essentially use the same steps to create the Add Todo button, renamed as Delete Todo, in the HTML doc. Then select the <ul> element first by the get.ElementById('todoList'); and then target a particular todo item with its index number through the .removeChild(); function...?	

#3 
http://codepen.io/jennvking/pen/wdWaGq
Questions
1. What is the function of document.getElementsByTagName?
This function should return a collection of all elements in the document with the specified tag name.
2. What is the purpose of the .reduce function?
Applying this function returns the sum of the numbers in an array.
3. What is the purpose of the setAttribute method?
The .setAttribute adds a specified attribute to an element, then specifies a value. For this js doc, the text box is type in and the value is numeric.

**Comment by seancahall** [comment]
Good work!
